version: "3.8"

services:
  app:
    build: .
    container_name: pki-2fa-service
    ports:
      - "8080:8080"

    # Persistent storage inside container â†’ /data
    volumes:
      - seed-data:/data
      - cron-output:/cron

      # PKI Keys (read-only)
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro

      # Optional: encrypted seed (if needed for boot-time decryption)
      - ./encrypted_seed.txt:/app/encrypted_seed.txt:ro

    environment:
      TZ: "UTC"

    restart: unless-stopped

volumes:
  seed-data:
  cron-output:

